#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
#include "syscall.h"
struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(key_size, sizeof(u32));
    __uint(value_size, sizeof(u32));
} output SEC(".maps");

struct kernel_tracepoints {
	unsigned short common_type;
    unsigned char common_flags;
    unsigned char common_preempt_count;
    int common_pid;

	long syscall_nr;
	void *filename_ptr;
	long argv_ptr;
	long envp_ptr;
};

//로직 매크로
//syscall_name: 모니터링 할 커널 트레이스 포인트
//tp_name: message에 출력할 메세지(tp_내용으로 통일)
#define TRACE_SYSCALL(syscall_name, tp_name) \
int trace_##syscall_name(struct kernel_tracepoints *ctx) { \
    struct data_t data = {}; \
    bpf_probe_read_kernel(&data.message, sizeof(data.message), tp_name); \
    bpf_printk(#syscall_name); \
    data.pid = bpf_get_current_pid_tgid() >> 32; \
    data.uid = bpf_get_current_uid_gid() & 0xFFFFFFFF; \
    bpf_get_current_comm(&data.command, sizeof(data.command)); \
    bpf_perf_event_output(ctx, &output, BPF_F_CURRENT_CPU, &data, sizeof(data)); \
    return 0; \
}

SEC("tp/syscalls/sys_enter_llistxattr")
TRACE_SYSCALL(sys_enter_llistxattr, "tp_llistxattr")
SEC("tp/syscalls/sys_enter_setgroups")
TRACE_SYSCALL(sys_enter_setgroups, "tp_setgroups")
SEC("tp/syscalls/sys_exit_fstatfs")
TRACE_SYSCALL(sys_exit_fstatfs, "tp_fstatfs")
SEC("tp/syscalls/sys_exit_process_vm_writev")
TRACE_SYSCALL(sys_exit_process_vm_writev, "tp_writev")
SEC("tp/syscalls/sys_enter_lremovexattr")
TRACE_SYSCALL(sys_enter_lremovexattr, "tp_lremovexattr")
SEC("tp/syscalls/sys_enter_sethostname")
TRACE_SYSCALL(sys_enter_sethostname, "tp_sethostname")
SEC("tp/syscalls/sys_exit_fsync")
TRACE_SYSCALL(sys_exit_fsync, "tp_fsync")
SEC("tp/syscalls/sys_exit_pselect6")
TRACE_SYSCALL(sys_exit_pselect6, "tp_pselect6")
SEC("tp/syscalls/sys_enter_accept")
TRACE_SYSCALL(sys_enter_accept, "tp_accept")
SEC("tp/syscalls/sys_enter_lseek")
TRACE_SYSCALL(sys_enter_lseek, "tp_lseek")
SEC("tp/syscalls/sys_enter_setitimer")
TRACE_SYSCALL(sys_enter_setitimer, "tp_setitimer")
SEC("tp/syscalls/sys_exit_ftruncate")
TRACE_SYSCALL(sys_exit_ftruncate, "tp_ftruncate")
SEC("tp/syscalls/sys_exit_ptrace")
TRACE_SYSCALL(sys_exit_ptrace, "tp_ptrace")
SEC("tp/syscalls/sys_enter_accept4")
TRACE_SYSCALL(sys_enter_accept4, "tp_accept4")
SEC("tp/syscalls/sys_enter_lsetxattr")
TRACE_SYSCALL(sys_enter_lsetxattr, "tp_lsetxattr")
SEC("tp/syscalls/sys_enter_setns")
TRACE_SYSCALL(sys_enter_setns, "tp_setns")
SEC("tp/syscalls/sys_exit_futex")
TRACE_SYSCALL(sys_exit_futex, "tp_futex")
SEC("tp/syscalls/sys_exit_pwrite64")
TRACE_SYSCALL(sys_exit_pwrite64, "tp_pwrite64")
SEC("tp/syscalls/sys_enter_acct")
TRACE_SYSCALL(sys_enter_acct, "tp_acct")
SEC("tp/syscalls/sys_enter_madvise")
TRACE_SYSCALL(sys_enter_madvise, "tp_madvise")
SEC("tp/syscalls/sys_enter_setpgid")
TRACE_SYSCALL(sys_enter_setpgid, "tp_setpgid")
SEC("tp/syscalls/sys_exit_get_mempolicy")
TRACE_SYSCALL(sys_exit_get_mempolicy, "tp_mempolicy")
SEC("tp/syscalls/sys_exit_pwritev")
TRACE_SYSCALL(sys_exit_pwritev, "tp_pwritev")
SEC("tp/syscalls/sys_enter_add_key")
TRACE_SYSCALL(sys_enter_add_key, "tp_key")
SEC("tp/syscalls/sys_enter_mbind")
TRACE_SYSCALL(sys_enter_mbind, "tp_mbind")
SEC("tp/syscalls/sys_enter_setpriority")
TRACE_SYSCALL(sys_enter_setpriority, "tp_setpriority")
SEC("tp/syscalls/sys_exit_get_robust_list")
TRACE_SYSCALL(sys_exit_get_robust_list, "tp_list")
SEC("tp/syscalls/sys_exit_pwritev2")
TRACE_SYSCALL(sys_exit_pwritev2, "tp_pwritev2")
SEC("tp/syscalls/sys_enter_adjtimex")
TRACE_SYSCALL(sys_enter_adjtimex, "tp_adjtimex")
SEC("tp/syscalls/sys_enter_membarrier")
TRACE_SYSCALL(sys_enter_membarrier, "tp_membarrier")
SEC("tp/syscalls/sys_enter_setregid")
TRACE_SYSCALL(sys_enter_setregid, "tp_setregid")
SEC("tp/syscalls/sys_exit_getcpu")
TRACE_SYSCALL(sys_exit_getcpu, "tp_getcpu")
SEC("tp/syscalls/sys_exit_quotactl")
TRACE_SYSCALL(sys_exit_quotactl, "tp_quotactl")
SEC("tp/syscalls/sys_enter_arm64_personality")
TRACE_SYSCALL(sys_enter_arm64_personality, "tp_personality")
SEC("tp/syscalls/sys_enter_memfd_create")
TRACE_SYSCALL(sys_enter_memfd_create, "tp_create")
SEC("tp/syscalls/sys_enter_setresgid")
TRACE_SYSCALL(sys_enter_setresgid, "tp_setresgid")
SEC("tp/syscalls/sys_exit_getcwd")
TRACE_SYSCALL(sys_exit_getcwd, "tp_getcwd")
SEC("tp/syscalls/sys_exit_quotactl_fd")
TRACE_SYSCALL(sys_exit_quotactl_fd, "tp_fd")
SEC("tp/syscalls/sys_enter_bind")
TRACE_SYSCALL(sys_enter_bind, "tp_bind")
SEC("tp/syscalls/sys_enter_memfd_secret")
TRACE_SYSCALL(sys_enter_memfd_secret, "tp_secret")
SEC("tp/syscalls/sys_enter_setresuid")
TRACE_SYSCALL(sys_enter_setresuid, "tp_setresuid")
SEC("tp/syscalls/sys_exit_getdents64")
TRACE_SYSCALL(sys_exit_getdents64, "tp_getdents64")
SEC("tp/syscalls/sys_exit_read")
TRACE_SYSCALL(sys_exit_read, "tp_read")
SEC("tp/syscalls/sys_enter_bpf")
TRACE_SYSCALL(sys_enter_bpf, "tp_bpf")
SEC("tp/syscalls/sys_enter_migrate_pages")
TRACE_SYSCALL(sys_enter_migrate_pages, "tp_pages")
SEC("tp/syscalls/sys_enter_setreuid")
TRACE_SYSCALL(sys_enter_setreuid, "tp_setreuid")
SEC("tp/syscalls/sys_exit_getegid")
TRACE_SYSCALL(sys_exit_getegid, "tp_getegid")
SEC("tp/syscalls/sys_exit_readahead")
TRACE_SYSCALL(sys_exit_readahead, "tp_readahead")
SEC("tp/syscalls/sys_enter_brk")
TRACE_SYSCALL(sys_enter_brk, "tp_brk")
SEC("tp/syscalls/sys_enter_mincore")
TRACE_SYSCALL(sys_enter_mincore, "tp_mincore")
SEC("tp/syscalls/sys_enter_setrlimit")
TRACE_SYSCALL(sys_enter_setrlimit, "tp_setrlimit")
SEC("tp/syscalls/sys_exit_geteuid")
TRACE_SYSCALL(sys_exit_geteuid, "tp_geteuid")
SEC("tp/syscalls/sys_exit_readlinkat")
TRACE_SYSCALL(sys_exit_readlinkat, "tp_readlinkat")
SEC("tp/syscalls/sys_enter_capget")
TRACE_SYSCALL(sys_enter_capget, "tp_capget")
SEC("tp/syscalls/sys_enter_mkdirat")
TRACE_SYSCALL(sys_enter_mkdirat, "tp_mkdirat")
SEC("tp/syscalls/sys_enter_setsid")
TRACE_SYSCALL(sys_enter_setsid, "tp_setsid")
SEC("tp/syscalls/sys_exit_getgid")
TRACE_SYSCALL(sys_exit_getgid, "tp_getgid")
SEC("tp/syscalls/sys_exit_readv")
TRACE_SYSCALL(sys_exit_readv, "tp_readv")
SEC("tp/syscalls/sys_enter_capset")
TRACE_SYSCALL(sys_enter_capset, "tp_capset")
SEC("tp/syscalls/sys_enter_mknodat")
TRACE_SYSCALL(sys_enter_mknodat, "tp_mknodat")
SEC("tp/syscalls/sys_enter_setsockopt")
TRACE_SYSCALL(sys_enter_setsockopt, "tp_setsockopt")
SEC("tp/syscalls/sys_exit_getgroups")
TRACE_SYSCALL(sys_exit_getgroups, "tp_getgroups")
SEC("tp/syscalls/sys_exit_reboot")
TRACE_SYSCALL(sys_exit_reboot, "tp_reboot")
SEC("tp/syscalls/sys_enter_chdir")
TRACE_SYSCALL(sys_enter_chdir, "tp_chdir")
SEC("tp/syscalls/sys_enter_mlock")
TRACE_SYSCALL(sys_enter_mlock, "tp_mlock")
SEC("tp/syscalls/sys_enter_settimeofday")
TRACE_SYSCALL(sys_enter_settimeofday, "tp_settimeofday")
SEC("tp/syscalls/sys_exit_getitimer")
TRACE_SYSCALL(sys_exit_getitimer, "tp_getitimer")
SEC("tp/syscalls/sys_exit_recvfrom")
TRACE_SYSCALL(sys_exit_recvfrom, "tp_recvfrom")
SEC("tp/syscalls/sys_enter_chroot")
TRACE_SYSCALL(sys_enter_chroot, "tp_chroot")
SEC("tp/syscalls/sys_enter_mlock2")
TRACE_SYSCALL(sys_enter_mlock2, "tp_mlock2")
SEC("tp/syscalls/sys_enter_setuid")
TRACE_SYSCALL(sys_enter_setuid, "tp_setuid")
SEC("tp/syscalls/sys_exit_getpeername")
TRACE_SYSCALL(sys_exit_getpeername, "tp_getpeername")
SEC("tp/syscalls/sys_exit_recvmmsg")
TRACE_SYSCALL(sys_exit_recvmmsg, "tp_recvmmsg")
SEC("tp/syscalls/sys_enter_clock_adjtime")
TRACE_SYSCALL(sys_enter_clock_adjtime, "tp_adjtime")
SEC("tp/syscalls/sys_enter_mlockall")
TRACE_SYSCALL(sys_enter_mlockall, "tp_mlockall")
SEC("tp/syscalls/sys_enter_setxattr")
TRACE_SYSCALL(sys_enter_setxattr, "tp_setxattr")
SEC("tp/syscalls/sys_exit_getpgid")
TRACE_SYSCALL(sys_exit_getpgid, "tp_getpgid")
SEC("tp/syscalls/sys_exit_recvmsg")
TRACE_SYSCALL(sys_exit_recvmsg, "tp_recvmsg")
SEC("tp/syscalls/sys_enter_clock_getres")
TRACE_SYSCALL(sys_enter_clock_getres, "tp_getres")
SEC("tp/syscalls/sys_enter_mmap")
TRACE_SYSCALL(sys_enter_mmap, "tp_mmap")
SEC("tp/syscalls/sys_enter_shmat")
TRACE_SYSCALL(sys_enter_shmat, "tp_shmat")
SEC("tp/syscalls/sys_exit_getpid")
TRACE_SYSCALL(sys_exit_getpid, "tp_getpid")
SEC("tp/syscalls/sys_exit_remap_file_pages")
TRACE_SYSCALL(sys_exit_remap_file_pages, "tp_pages")
SEC("tp/syscalls/sys_enter_clock_gettime")
TRACE_SYSCALL(sys_enter_clock_gettime, "tp_gettime")
SEC("tp/syscalls/sys_enter_mount")
TRACE_SYSCALL(sys_enter_mount, "tp_mount")
SEC("tp/syscalls/sys_enter_shmctl")
TRACE_SYSCALL(sys_enter_shmctl, "tp_shmctl")
SEC("tp/syscalls/sys_exit_getppid")
TRACE_SYSCALL(sys_exit_getppid, "tp_getppid")
SEC("tp/syscalls/sys_exit_removexattr")
TRACE_SYSCALL(sys_exit_removexattr, "tp_removexattr")
SEC("tp/syscalls/sys_enter_clock_nanosleep")
TRACE_SYSCALL(sys_enter_clock_nanosleep, "tp_nanosleep")
SEC("tp/syscalls/sys_enter_mount_setattr")
TRACE_SYSCALL(sys_enter_mount_setattr, "tp_setattr")
SEC("tp/syscalls/sys_enter_shmdt")
TRACE_SYSCALL(sys_enter_shmdt, "tp_shmdt")
SEC("tp/syscalls/sys_exit_getpriority")
TRACE_SYSCALL(sys_exit_getpriority, "tp_getpriority")
SEC("tp/syscalls/sys_exit_renameat")
TRACE_SYSCALL(sys_exit_renameat, "tp_renameat")
SEC("tp/syscalls/sys_enter_clock_settime")
TRACE_SYSCALL(sys_enter_clock_settime, "tp_settime")
SEC("tp/syscalls/sys_enter_move_mount")
TRACE_SYSCALL(sys_enter_move_mount, "tp_mount")
SEC("tp/syscalls/sys_enter_shmget")
TRACE_SYSCALL(sys_enter_shmget, "tp_shmget")
SEC("tp/syscalls/sys_exit_getrandom")
TRACE_SYSCALL(sys_exit_getrandom, "tp_getrandom")
SEC("tp/syscalls/sys_exit_renameat2")
TRACE_SYSCALL(sys_exit_renameat2, "tp_renameat2")
SEC("tp/syscalls/sys_enter_clone")
TRACE_SYSCALL(sys_enter_clone, "tp_clone")
SEC("tp/syscalls/sys_enter_move_pages")
TRACE_SYSCALL(sys_enter_move_pages, "tp_pages")
SEC("tp/syscalls/sys_enter_shutdown")
TRACE_SYSCALL(sys_enter_shutdown, "tp_shutdown")
SEC("tp/syscalls/sys_exit_getresgid")
TRACE_SYSCALL(sys_exit_getresgid, "tp_getresgid")
SEC("tp/syscalls/sys_exit_request_key")
TRACE_SYSCALL(sys_exit_request_key, "tp_key")
SEC("tp/syscalls/sys_enter_clone3")
TRACE_SYSCALL(sys_enter_clone3, "tp_clone3")
SEC("tp/syscalls/sys_enter_mprotect")
TRACE_SYSCALL(sys_enter_mprotect, "tp_mprotect")
SEC("tp/syscalls/sys_enter_sigaltstack")
TRACE_SYSCALL(sys_enter_sigaltstack, "tp_sigaltstack")
SEC("tp/syscalls/sys_exit_getresuid")
TRACE_SYSCALL(sys_exit_getresuid, "tp_getresuid")
SEC("tp/syscalls/sys_exit_restart_syscall")
TRACE_SYSCALL(sys_exit_restart_syscall, "tp_syscall")
SEC("tp/syscalls/sys_enter_close")
TRACE_SYSCALL(sys_enter_close, "tp_close")
SEC("tp/syscalls/sys_enter_mq_getsetattr")
TRACE_SYSCALL(sys_enter_mq_getsetattr, "tp_getsetattr")
SEC("tp/syscalls/sys_enter_signalfd4")
TRACE_SYSCALL(sys_enter_signalfd4, "tp_signalfd4")
SEC("tp/syscalls/sys_exit_getrlimit")
TRACE_SYSCALL(sys_exit_getrlimit, "tp_getrlimit")
SEC("tp/syscalls/sys_exit_rseq")
TRACE_SYSCALL(sys_exit_rseq, "tp_rseq")
SEC("tp/syscalls/sys_enter_close_range")
TRACE_SYSCALL(sys_enter_close_range, "tp_range")
SEC("tp/syscalls/sys_enter_mq_notify")
TRACE_SYSCALL(sys_enter_mq_notify, "tp_notify")
SEC("tp/syscalls/sys_enter_socket")
TRACE_SYSCALL(sys_enter_socket, "tp_socket")
SEC("tp/syscalls/sys_exit_getrusage")
TRACE_SYSCALL(sys_exit_getrusage, "tp_getrusage")
SEC("tp/syscalls/sys_exit_rt_sigaction")
TRACE_SYSCALL(sys_exit_rt_sigaction, "tp_sigaction")
SEC("tp/syscalls/sys_enter_connect")
TRACE_SYSCALL(sys_enter_connect, "tp_connect")
SEC("tp/syscalls/sys_enter_mq_open")
TRACE_SYSCALL(sys_enter_mq_open, "tp_open")
SEC("tp/syscalls/sys_enter_socketpair")
TRACE_SYSCALL(sys_enter_socketpair, "tp_socketpair")
SEC("tp/syscalls/sys_exit_getsid")
TRACE_SYSCALL(sys_exit_getsid, "tp_getsid")
SEC("tp/syscalls/sys_exit_rt_sigpending")
TRACE_SYSCALL(sys_exit_rt_sigpending, "tp_sigpending")
SEC("tp/syscalls/sys_enter_copy_file_range")
TRACE_SYSCALL(sys_enter_copy_file_range, "tp_range")
SEC("tp/syscalls/sys_enter_mq_timedreceive")
TRACE_SYSCALL(sys_enter_mq_timedreceive, "tp_timedreceive")
SEC("tp/syscalls/sys_enter_splice")
TRACE_SYSCALL(sys_enter_splice, "tp_splice")
SEC("tp/syscalls/sys_exit_getsockname")
TRACE_SYSCALL(sys_exit_getsockname, "tp_getsockname")
SEC("tp/syscalls/sys_exit_rt_sigprocmask")
TRACE_SYSCALL(sys_exit_rt_sigprocmask, "tp_sigprocmask")
SEC("tp/syscalls/sys_enter_delete_module")
TRACE_SYSCALL(sys_enter_delete_module, "tp_module")
SEC("tp/syscalls/sys_enter_mq_timedsend")
TRACE_SYSCALL(sys_enter_mq_timedsend, "tp_timedsend")
SEC("tp/syscalls/sys_enter_statfs")
TRACE_SYSCALL(sys_enter_statfs, "tp_statfs")
SEC("tp/syscalls/sys_exit_getsockopt")
TRACE_SYSCALL(sys_exit_getsockopt, "tp_getsockopt")
SEC("tp/syscalls/sys_exit_rt_sigqueueinfo")
TRACE_SYSCALL(sys_exit_rt_sigqueueinfo, "tp_sigqueueinfo")
SEC("tp/syscalls/sys_enter_dup")
TRACE_SYSCALL(sys_enter_dup, "tp_dup")
SEC("tp/syscalls/sys_enter_mq_unlink")
TRACE_SYSCALL(sys_enter_mq_unlink, "tp_unlink")
SEC("tp/syscalls/sys_enter_statx")
TRACE_SYSCALL(sys_enter_statx, "tp_statx")
SEC("tp/syscalls/sys_exit_gettid")
TRACE_SYSCALL(sys_exit_gettid, "tp_gettid")
SEC("tp/syscalls/sys_exit_rt_sigreturn")
TRACE_SYSCALL(sys_exit_rt_sigreturn, "tp_sigreturn")
SEC("tp/syscalls/sys_enter_dup3")
TRACE_SYSCALL(sys_enter_dup3, "tp_dup3")
SEC("tp/syscalls/sys_enter_mremap")
TRACE_SYSCALL(sys_enter_mremap, "tp_mremap")
SEC("tp/syscalls/sys_enter_swapoff")
TRACE_SYSCALL(sys_enter_swapoff, "tp_swapoff")
SEC("tp/syscalls/sys_exit_gettimeofday")
TRACE_SYSCALL(sys_exit_gettimeofday, "tp_gettimeofday")
SEC("tp/syscalls/sys_exit_rt_sigsuspend")
TRACE_SYSCALL(sys_exit_rt_sigsuspend, "tp_sigsuspend")
SEC("tp/syscalls/sys_enter_epoll_create1")
TRACE_SYSCALL(sys_enter_epoll_create1, "tp_create1")
SEC("tp/syscalls/sys_enter_msgctl")
TRACE_SYSCALL(sys_enter_msgctl, "tp_msgctl")
SEC("tp/syscalls/sys_enter_swapon")
TRACE_SYSCALL(sys_enter_swapon, "tp_swapon")
SEC("tp/syscalls/sys_exit_getuid")
TRACE_SYSCALL(sys_exit_getuid, "tp_getuid")
SEC("tp/syscalls/sys_exit_rt_sigtimedwait")
TRACE_SYSCALL(sys_exit_rt_sigtimedwait, "tp_sigtimedwait")
SEC("tp/syscalls/sys_enter_epoll_ctl")
TRACE_SYSCALL(sys_enter_epoll_ctl, "tp_ctl")
SEC("tp/syscalls/sys_enter_msgget")
TRACE_SYSCALL(sys_enter_msgget, "tp_msgget")
SEC("tp/syscalls/sys_enter_symlinkat")
TRACE_SYSCALL(sys_enter_symlinkat, "tp_symlinkat")
SEC("tp/syscalls/sys_exit_getxattr")
TRACE_SYSCALL(sys_exit_getxattr, "tp_getxattr")
SEC("tp/syscalls/sys_exit_rt_tgsigqueueinfo")
TRACE_SYSCALL(sys_exit_rt_tgsigqueueinfo, "tp_tgsigqueueinfo")
SEC("tp/syscalls/sys_enter_epoll_pwait")
TRACE_SYSCALL(sys_enter_epoll_pwait, "tp_pwait")
SEC("tp/syscalls/sys_enter_msgrcv")
TRACE_SYSCALL(sys_enter_msgrcv, "tp_msgrcv")
SEC("tp/syscalls/sys_enter_sync")
TRACE_SYSCALL(sys_enter_sync, "tp_sync")
SEC("tp/syscalls/sys_exit_init_module")
TRACE_SYSCALL(sys_exit_init_module, "tp_module")
SEC("tp/syscalls/sys_exit_sched_get_priority_max")
TRACE_SYSCALL(sys_exit_sched_get_priority_max, "tp_max")
SEC("tp/syscalls/sys_enter_epoll_pwait2")
TRACE_SYSCALL(sys_enter_epoll_pwait2, "tp_pwait2")
SEC("tp/syscalls/sys_enter_msgsnd")
TRACE_SYSCALL(sys_enter_msgsnd, "tp_msgsnd")
SEC("tp/syscalls/sys_enter_sync_file_range")
TRACE_SYSCALL(sys_enter_sync_file_range, "tp_range")
SEC("tp/syscalls/sys_exit_inotify_add_watch")
TRACE_SYSCALL(sys_exit_inotify_add_watch, "tp_watch")
SEC("tp/syscalls/sys_exit_sched_get_priority_min")
TRACE_SYSCALL(sys_exit_sched_get_priority_min, "tp_min")
SEC("tp/syscalls/sys_enter_eventfd2")
TRACE_SYSCALL(sys_enter_eventfd2, "tp_eventfd2")
SEC("tp/syscalls/sys_enter_msync")
TRACE_SYSCALL(sys_enter_msync, "tp_msync")
SEC("tp/syscalls/sys_enter_syncfs")
TRACE_SYSCALL(sys_enter_syncfs, "tp_syncfs")
SEC("tp/syscalls/sys_exit_inotify_init1")
TRACE_SYSCALL(sys_exit_inotify_init1, "tp_init1")
SEC("tp/syscalls/sys_exit_sched_getaffinity")
TRACE_SYSCALL(sys_exit_sched_getaffinity, "tp_getaffinity")
SEC("tp/syscalls/sys_enter_execve")
TRACE_SYSCALL(sys_enter_execve, "tp_execve")
SEC("tp/syscalls/sys_enter_munlock")
TRACE_SYSCALL(sys_enter_munlock, "tp_munlock")
SEC("tp/syscalls/sys_enter_sysinfo")
TRACE_SYSCALL(sys_enter_sysinfo, "tp_sysinfo")
SEC("tp/syscalls/sys_exit_inotify_rm_watch")
TRACE_SYSCALL(sys_exit_inotify_rm_watch, "tp_watch")
SEC("tp/syscalls/sys_exit_sched_getattr")
TRACE_SYSCALL(sys_exit_sched_getattr, "tp_getattr")
SEC("tp/syscalls/sys_enter_execveat")
TRACE_SYSCALL(sys_enter_execveat, "tp_execveat")
SEC("tp/syscalls/sys_enter_munlockall")
TRACE_SYSCALL(sys_enter_munlockall, "tp_munlockall")
SEC("tp/syscalls/sys_enter_syslog")
TRACE_SYSCALL(sys_enter_syslog, "tp_syslog")
SEC("tp/syscalls/sys_exit_io_cancel")
TRACE_SYSCALL(sys_exit_io_cancel, "tp_cancel")
SEC("tp/syscalls/sys_exit_sched_getparam")
TRACE_SYSCALL(sys_exit_sched_getparam, "tp_getparam")
SEC("tp/syscalls/sys_enter_exit")
TRACE_SYSCALL(sys_enter_exit, "tp_exit")
SEC("tp/syscalls/sys_enter_munmap")
TRACE_SYSCALL(sys_enter_munmap, "tp_munmap")
SEC("tp/syscalls/sys_enter_tee")
TRACE_SYSCALL(sys_enter_tee, "tp_tee")
SEC("tp/syscalls/sys_exit_io_destroy")
TRACE_SYSCALL(sys_exit_io_destroy, "tp_destroy")
SEC("tp/syscalls/sys_exit_sched_getscheduler")
TRACE_SYSCALL(sys_exit_sched_getscheduler, "tp_getscheduler")
SEC("tp/syscalls/sys_enter_exit_group")
TRACE_SYSCALL(sys_enter_exit_group, "tp_group")
SEC("tp/syscalls/sys_enter_name_to_handle_at")
TRACE_SYSCALL(sys_enter_name_to_handle_at, "tp_at")
SEC("tp/syscalls/sys_enter_tgkill")
TRACE_SYSCALL(sys_enter_tgkill, "tp_tgkill")
SEC("tp/syscalls/sys_exit_io_getevents")
TRACE_SYSCALL(sys_exit_io_getevents, "tp_getevents")
SEC("tp/syscalls/sys_exit_sched_rr_get_interval")
TRACE_SYSCALL(sys_exit_sched_rr_get_interval, "tp_interval")
SEC("tp/syscalls/sys_enter_faccessat")
TRACE_SYSCALL(sys_enter_faccessat, "tp_faccessat")
SEC("tp/syscalls/sys_enter_nanosleep")
TRACE_SYSCALL(sys_enter_nanosleep, "tp_nanosleep")
SEC("tp/syscalls/sys_enter_timer_create")
TRACE_SYSCALL(sys_enter_timer_create, "tp_create")
SEC("tp/syscalls/sys_exit_io_pgetevents")
TRACE_SYSCALL(sys_exit_io_pgetevents, "tp_pgetevents")
SEC("tp/syscalls/sys_exit_sched_setaffinity")
TRACE_SYSCALL(sys_exit_sched_setaffinity, "tp_setaffinity")
SEC("tp/syscalls/sys_enter_faccessat2")
TRACE_SYSCALL(sys_enter_faccessat2, "tp_faccessat2")
SEC("tp/syscalls/sys_enter_newfstat")
TRACE_SYSCALL(sys_enter_newfstat, "tp_newfstat")
SEC("tp/syscalls/sys_enter_timer_delete")
TRACE_SYSCALL(sys_enter_timer_delete, "tp_delete")
SEC("tp/syscalls/sys_exit_io_setup")
TRACE_SYSCALL(sys_exit_io_setup, "tp_setup")
SEC("tp/syscalls/sys_exit_sched_setattr")
TRACE_SYSCALL(sys_exit_sched_setattr, "tp_setattr")
SEC("tp/syscalls/sys_enter_fadvise64_64")
TRACE_SYSCALL(sys_enter_fadvise64_64, "tp_64")
SEC("tp/syscalls/sys_enter_newfstatat")
TRACE_SYSCALL(sys_enter_newfstatat, "tp_newfstatat")
SEC("tp/syscalls/sys_enter_timer_getoverrun")
TRACE_SYSCALL(sys_enter_timer_getoverrun, "tp_getoverrun")
SEC("tp/syscalls/sys_exit_io_submit")
TRACE_SYSCALL(sys_exit_io_submit, "tp_submit")
SEC("tp/syscalls/sys_exit_sched_setparam")
TRACE_SYSCALL(sys_exit_sched_setparam, "tp_setparam")
SEC("tp/syscalls/sys_enter_fallocate")
TRACE_SYSCALL(sys_enter_fallocate, "tp_fallocate")
SEC("tp/syscalls/sys_enter_newuname")
TRACE_SYSCALL(sys_enter_newuname, "tp_newuname")
SEC("tp/syscalls/sys_enter_timer_gettime")
TRACE_SYSCALL(sys_enter_timer_gettime, "tp_gettime")
SEC("tp/syscalls/sys_exit_io_uring_enter")
TRACE_SYSCALL(sys_exit_io_uring_enter, "tp_enter")
SEC("tp/syscalls/sys_exit_sched_setscheduler")
TRACE_SYSCALL(sys_exit_sched_setscheduler, "tp_setscheduler")
SEC("tp/syscalls/sys_enter_fanotify_init")
TRACE_SYSCALL(sys_enter_fanotify_init, "tp_init")
SEC("tp/syscalls/sys_enter_open_by_handle_at")
TRACE_SYSCALL(sys_enter_open_by_handle_at, "tp_at")
SEC("tp/syscalls/sys_enter_timer_settime")
TRACE_SYSCALL(sys_enter_timer_settime, "tp_settime")
SEC("tp/syscalls/sys_exit_io_uring_register")
TRACE_SYSCALL(sys_exit_io_uring_register, "tp_register")
SEC("tp/syscalls/sys_exit_sched_yield")
TRACE_SYSCALL(sys_exit_sched_yield, "tp_yield")
SEC("tp/syscalls/sys_enter_fanotify_mark")
TRACE_SYSCALL(sys_enter_fanotify_mark, "tp_mark")
SEC("tp/syscalls/sys_enter_open_tree")
TRACE_SYSCALL(sys_enter_open_tree, "tp_tree")
SEC("tp/syscalls/sys_enter_timerfd_create")
TRACE_SYSCALL(sys_enter_timerfd_create, "tp_create")
SEC("tp/syscalls/sys_exit_io_uring_setup")
TRACE_SYSCALL(sys_exit_io_uring_setup, "tp_setup")
SEC("tp/syscalls/sys_exit_seccomp")
TRACE_SYSCALL(sys_exit_seccomp, "tp_seccomp")
SEC("tp/syscalls/sys_enter_fchdir")
TRACE_SYSCALL(sys_enter_fchdir, "tp_fchdir")
SEC("tp/syscalls/sys_enter_openat")
TRACE_SYSCALL(sys_enter_openat, "tp_openat")
SEC("tp/syscalls/sys_enter_timerfd_gettime")
TRACE_SYSCALL(sys_enter_timerfd_gettime, "tp_gettime")
SEC("tp/syscalls/sys_exit_ioctl")
TRACE_SYSCALL(sys_exit_ioctl, "tp_ioctl")
SEC("tp/syscalls/sys_exit_semctl")
TRACE_SYSCALL(sys_exit_semctl, "tp_semctl")
SEC("tp/syscalls/sys_enter_fchmod")
TRACE_SYSCALL(sys_enter_fchmod, "tp_fchmod")
SEC("tp/syscalls/sys_enter_openat2")
TRACE_SYSCALL(sys_enter_openat2, "tp_openat2")
SEC("tp/syscalls/sys_enter_timerfd_settime")
TRACE_SYSCALL(sys_enter_timerfd_settime, "tp_settime")
SEC("tp/syscalls/sys_exit_ioprio_get")
TRACE_SYSCALL(sys_exit_ioprio_get, "tp_get")
SEC("tp/syscalls/sys_exit_semget")
TRACE_SYSCALL(sys_exit_semget, "tp_semget")
SEC("tp/syscalls/sys_enter_fchmodat")
TRACE_SYSCALL(sys_enter_fchmodat, "tp_fchmodat")
SEC("tp/syscalls/sys_enter_perf_event_open")
TRACE_SYSCALL(sys_enter_perf_event_open, "tp_open")
SEC("tp/syscalls/sys_enter_times")
TRACE_SYSCALL(sys_enter_times, "tp_times")
SEC("tp/syscalls/sys_exit_ioprio_set")
TRACE_SYSCALL(sys_exit_ioprio_set, "tp_set")
SEC("tp/syscalls/sys_exit_semop")
TRACE_SYSCALL(sys_exit_semop, "tp_semop")
SEC("tp/syscalls/sys_enter_fchown")
TRACE_SYSCALL(sys_enter_fchown, "tp_fchown")
SEC("tp/syscalls/sys_enter_pidfd_getfd")
TRACE_SYSCALL(sys_enter_pidfd_getfd, "tp_getfd")
SEC("tp/syscalls/sys_enter_tkill")
TRACE_SYSCALL(sys_enter_tkill, "tp_tkill")
SEC("tp/syscalls/sys_exit_kcmp")
TRACE_SYSCALL(sys_exit_kcmp, "tp_kcmp")
SEC("tp/syscalls/sys_exit_semtimedop")
TRACE_SYSCALL(sys_exit_semtimedop, "tp_semtimedop")
SEC("tp/syscalls/sys_enter_fchownat")
TRACE_SYSCALL(sys_enter_fchownat, "tp_fchownat")
SEC("tp/syscalls/sys_enter_pidfd_open")
TRACE_SYSCALL(sys_enter_pidfd_open, "tp_open")
SEC("tp/syscalls/sys_enter_truncate")
TRACE_SYSCALL(sys_enter_truncate, "tp_truncate")
SEC("tp/syscalls/sys_exit_kexec_file_load")
TRACE_SYSCALL(sys_exit_kexec_file_load, "tp_load")
SEC("tp/syscalls/sys_exit_sendfile64")
TRACE_SYSCALL(sys_exit_sendfile64, "tp_sendfile64")
SEC("tp/syscalls/sys_enter_fcntl")
TRACE_SYSCALL(sys_enter_fcntl, "tp_fcntl")
SEC("tp/syscalls/sys_enter_pidfd_send_signal")
TRACE_SYSCALL(sys_enter_pidfd_send_signal, "tp_signal")
SEC("tp/syscalls/sys_enter_umask")
TRACE_SYSCALL(sys_enter_umask, "tp_umask")
SEC("tp/syscalls/sys_exit_kexec_load")
TRACE_SYSCALL(sys_exit_kexec_load, "tp_load")
SEC("tp/syscalls/sys_exit_sendmmsg")
TRACE_SYSCALL(sys_exit_sendmmsg, "tp_sendmmsg")
SEC("tp/syscalls/sys_enter_fdatasync")
TRACE_SYSCALL(sys_enter_fdatasync, "tp_fdatasync")
SEC("tp/syscalls/sys_enter_pipe2")
TRACE_SYSCALL(sys_enter_pipe2, "tp_pipe2")
SEC("tp/syscalls/sys_enter_umount")
TRACE_SYSCALL(sys_enter_umount, "tp_umount")
SEC("tp/syscalls/sys_exit_keyctl")
TRACE_SYSCALL(sys_exit_keyctl, "tp_keyctl")
SEC("tp/syscalls/sys_exit_sendmsg")
TRACE_SYSCALL(sys_exit_sendmsg, "tp_sendmsg")
SEC("tp/syscalls/sys_enter_fgetxattr")
TRACE_SYSCALL(sys_enter_fgetxattr, "tp_fgetxattr")
SEC("tp/syscalls/sys_enter_pivot_root")
TRACE_SYSCALL(sys_enter_pivot_root, "tp_root")
SEC("tp/syscalls/sys_enter_unlinkat")
TRACE_SYSCALL(sys_enter_unlinkat, "tp_unlinkat")
SEC("tp/syscalls/sys_exit_kill")
TRACE_SYSCALL(sys_exit_kill, "tp_kill")
SEC("tp/syscalls/sys_exit_sendto")
TRACE_SYSCALL(sys_exit_sendto, "tp_sendto")
SEC("tp/syscalls/sys_enter_finit_module")
TRACE_SYSCALL(sys_enter_finit_module, "tp_module")
SEC("tp/syscalls/sys_enter_ppoll")
TRACE_SYSCALL(sys_enter_ppoll, "tp_ppoll")
SEC("tp/syscalls/sys_enter_unshare")
TRACE_SYSCALL(sys_enter_unshare, "tp_unshare")
SEC("tp/syscalls/sys_exit_landlock_add_rule")
TRACE_SYSCALL(sys_exit_landlock_add_rule, "tp_rule")
SEC("tp/syscalls/sys_exit_set_mempolicy")
TRACE_SYSCALL(sys_exit_set_mempolicy, "tp_mempolicy")
SEC("tp/syscalls/sys_enter_flistxattr")
TRACE_SYSCALL(sys_enter_flistxattr, "tp_flistxattr")
SEC("tp/syscalls/sys_enter_prctl")
TRACE_SYSCALL(sys_enter_prctl, "tp_prctl")
SEC("tp/syscalls/sys_enter_userfaultfd")
TRACE_SYSCALL(sys_enter_userfaultfd, "tp_userfaultfd")
SEC("tp/syscalls/sys_exit_landlock_create_ruleset")
TRACE_SYSCALL(sys_exit_landlock_create_ruleset, "tp_ruleset")
SEC("tp/syscalls/sys_exit_set_robust_list")
TRACE_SYSCALL(sys_exit_set_robust_list, "tp_list")
SEC("tp/syscalls/sys_enter_flock")
TRACE_SYSCALL(sys_enter_flock, "tp_flock")
SEC("tp/syscalls/sys_enter_pread64")
TRACE_SYSCALL(sys_enter_pread64, "tp_pread64")
SEC("tp/syscalls/sys_enter_utimensat")
TRACE_SYSCALL(sys_enter_utimensat, "tp_utimensat")
SEC("tp/syscalls/sys_exit_landlock_restrict_self")
TRACE_SYSCALL(sys_exit_landlock_restrict_self, "tp_self")
SEC("tp/syscalls/sys_exit_set_tid_address")
TRACE_SYSCALL(sys_exit_set_tid_address, "tp_address")
SEC("tp/syscalls/sys_enter_fremovexattr")
TRACE_SYSCALL(sys_enter_fremovexattr, "tp_fremovexattr")
SEC("tp/syscalls/sys_enter_preadv")
TRACE_SYSCALL(sys_enter_preadv, "tp_preadv")
SEC("tp/syscalls/sys_enter_vhangup")
TRACE_SYSCALL(sys_enter_vhangup, "tp_vhangup")
SEC("tp/syscalls/sys_exit_lgetxattr")
TRACE_SYSCALL(sys_exit_lgetxattr, "tp_lgetxattr")
SEC("tp/syscalls/sys_exit_setdomainname")
TRACE_SYSCALL(sys_exit_setdomainname, "tp_setdomainname")
SEC("tp/syscalls/sys_enter_fsconfig")
TRACE_SYSCALL(sys_enter_fsconfig, "tp_fsconfig")
SEC("tp/syscalls/sys_enter_preadv2")
TRACE_SYSCALL(sys_enter_preadv2, "tp_preadv2")
SEC("tp/syscalls/sys_enter_vmsplice")
TRACE_SYSCALL(sys_enter_vmsplice, "tp_vmsplice")
SEC("tp/syscalls/sys_exit_linkat")
TRACE_SYSCALL(sys_exit_linkat, "tp_linkat")
SEC("tp/syscalls/sys_exit_setfsgid")
TRACE_SYSCALL(sys_exit_setfsgid, "tp_setfsgid")
SEC("tp/syscalls/sys_enter_fsetxattr")
TRACE_SYSCALL(sys_enter_fsetxattr, "tp_fsetxattr")
SEC("tp/syscalls/sys_enter_prlimit64")
TRACE_SYSCALL(sys_enter_prlimit64, "tp_prlimit64")
SEC("tp/syscalls/sys_enter_wait4")
TRACE_SYSCALL(sys_enter_wait4, "tp_wait4")
SEC("tp/syscalls/sys_exit_listen")
TRACE_SYSCALL(sys_exit_listen, "tp_listen")
SEC("tp/syscalls/sys_exit_setfsuid")
TRACE_SYSCALL(sys_exit_setfsuid, "tp_setfsuid")
SEC("tp/syscalls/sys_enter_fsmount")
TRACE_SYSCALL(sys_enter_fsmount, "tp_fsmount")
SEC("tp/syscalls/sys_enter_process_madvise")
TRACE_SYSCALL(sys_enter_process_madvise, "tp_madvise")
SEC("tp/syscalls/sys_enter_waitid")
TRACE_SYSCALL(sys_enter_waitid, "tp_waitid")
SEC("tp/syscalls/sys_exit_listxattr")
TRACE_SYSCALL(sys_exit_listxattr, "tp_listxattr")
SEC("tp/syscalls/sys_exit_setgid")
TRACE_SYSCALL(sys_exit_setgid, "tp_setgid")
SEC("tp/syscalls/sys_enter_fsopen")
TRACE_SYSCALL(sys_enter_fsopen, "tp_fsopen")
SEC("tp/syscalls/sys_enter_process_mrelease")
TRACE_SYSCALL(sys_enter_process_mrelease, "tp_mrelease")
SEC("tp/syscalls/sys_enter_write")
TRACE_SYSCALL(sys_enter_write, "tp_write")
SEC("tp/syscalls/sys_exit_llistxattr")
TRACE_SYSCALL(sys_exit_llistxattr, "tp_llistxattr")
SEC("tp/syscalls/sys_exit_setgroups")
TRACE_SYSCALL(sys_exit_setgroups, "tp_setgroups")
SEC("tp/syscalls/sys_enter_fspick")
TRACE_SYSCALL(sys_enter_fspick, "tp_fspick")


char LICENSE[] SEC("license") = "Dual BSD/GPL";